import React from "react";
import CategorySelect from "./CategorySelect";

export default function SearchBody() {
  return (
    <>
      <div className="py-1.5"></div>

      <div className="grid xl:grid-cols-8 lg:grid-cols-7 md:grid-cols-3 sm:grid-cols-2 gap-4">
        <CategorySelect
          category="Podcasts"
          image="https://picsum.photos/id/40/300/300"
        />
        <CategorySelect
          category="Made For You"
          image="https://picsum.photos/id/45/300/300"
        />
        <CategorySelect
          category="Charts"
          image="https://picsum.photos/id/76/300/300"
        />
        <CategorySelect
          category="New Release"
          image="https://picsum.photos/id/56/300/300"
        />
        <CategorySelect
          category="Discover"
          image="https://picsum.photos/id/25/300/300"
        />
        <CategorySelect
          category="Live Events"
          image="https://picsum.photos/id/103/300/300"
        />
        <CategorySelect
          category="Pop"
          image="https://picsum.photos/id/244/300/300"
        />
        <CategorySelect
          category="EQUAL"
          image="https://picsum.photos/id/202/300/300"
        />
        <CategorySelect
          category="Mood"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Decades"
          image="https://picsum.photos/id/120/300/300"
        />
        <CategorySelect
          category="Hip-Hop"
          image="https://picsum.photos/id/40/300/300"
        />
        <CategorySelect
          category="In The car"
          image="https://picsum.photos/id/45/300/300"
        />
        <CategorySelect
          category="Gaming"
          image="https://picsum.photos/id/76/300/300"
        />
        <CategorySelect
          category="Wellness"
          image="https://picsum.photos/id/56/300/300"
        />
        <CategorySelect
          category="League of Legends"
          image="https://picsum.photos/id/25/300/300"
        />
        <CategorySelect
          category="Workout"
          image="https://picsum.photos/id/103/300/300"
        />
        <CategorySelect
          category="Chill"
          image="https://picsum.photos/id/244/300/300"
        />
        <CategorySelect
          category="Focus"
          image="https://picsum.photos/id/202/300/300"
        />
        <CategorySelect
          category="Sleep"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Party"
          image="https://picsum.photos/id/120/300/300"
        />
        <CategorySelect
          category="Indie"
          image="https://picsum.photos/id/40/300/300"
        />
        <CategorySelect
          category="Metal"
          image="https://picsum.photos/id/45/300/300"
        />
        <CategorySelect
          category="Rock"
          image="https://picsum.photos/id/76/300/300"
        />
        <CategorySelect
          category="Dance/Electronic"
          image="https://picsum.photos/id/56/300/300"
        />
        <CategorySelect
          category="Cooking&Dining"
          image="https://picsum.photos/id/25/300/300"
        />
        <CategorySelect
          category="Jazz"
          image="https://picsum.photos/id/103/300/300"
        />
        <CategorySelect
          category="R&B"
          image="https://picsum.photos/id/244/300/300"
        />
        <CategorySelect
          category="Instrumental"
          image="https://picsum.photos/id/202/300/300"
        />
        <CategorySelect
          category="Romance"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Soul"
          image="https://picsum.photos/id/120/300/300"
        />
        <CategorySelect
          category="Kids & Family"
          image="https://picsum.photos/id/40/300/300"
        />
        <CategorySelect
          category="Classical"
          image="https://picsum.photos/id/45/300/300"
        />
        <CategorySelect
          category="Latin"
          image="https://picsum.photos/id/76/300/300"
        />
        <CategorySelect
          category="Songwriters"
          image="https://picsum.photos/id/56/300/300"
        />
        <CategorySelect
          category="Caribbean"
          image="https://picsum.photos/id/25/300/300"
        />
        <CategorySelect
          category="Blues"
          image="https://picsum.photos/id/103/300/300"
        />
        <CategorySelect
          category="Funk"
          image="https://picsum.photos/id/244/300/300"
        />
        <CategorySelect
          category="Punk"
          image="https://picsum.photos/id/202/300/300"
        />
        <CategorySelect
          category="Country"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Folk & Acoustic"
          image="https://picsum.photos/id/120/300/300"
        />
        <CategorySelect
          category="Desi"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Arad"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Afro"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Travel"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="K-Pop"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="TV & Movies"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Ambient"
          image="https://picsum.photos/id/101/300/300"
        />
      </div>
    </>
  );
}
